apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dab.labels" . | nindent 4 }}
    app.kubernetes.io/component: opensearch
spec:
  selector:
    app: opensearch
  ports:
  - port: {{ .Values.opensearch.port }}
    targetPort: {{ .Values.opensearch.port }}
    protocol: TCP
    name: http
  type: {{ .Values.opensearch.service.type }}
