apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: dab
spec:
  selector:
    app: opensearch
  ports:
  - port: {{ .Values.opensearch.port }}
    targetPort: {{ .Values.opensearch.port }}
